cni: multus,canal
cluster-cidr: 10.42.0.0/16,2001:db8:42::/48
service-cidr: 10.43.0.0/16,2001:db8:43::/112
cluster-dns: 10.43.0.10,2001:db8:43::a
tls-san:
  - {{ .Vip }}
{{if .SANS -}}
{{- range .SANS }}
  - {{ . }}
{{- end }}
{{- end }}
{{- with $args := .GetKubeletArgs }}
kubelet-arg:
{{- range $arg := $args }}
  - {{ printf "%q" $arg }}
{{- end }}
{{- end }}
audit-policy-file: /etc/rancher/rke2/config.yaml.d/92-harvester-kube-audit-policy.yaml